### PR TITLE
Update README.MD to Show Which Levels are Replaced

### PR DESCRIPTION
**Pull request by vanillaDSi**
Just a way to improve ease of access.

### CODE REVIEW

**Comment by Llennpie** [comment]
Did you mean to PR this on [GMM's custom maps fork](https://github.com/GlitchyMarioMario64/Saturn-Custom-Maps) and not the main Saturn repo?

**Comment by GlitchyMarioMario64** [comment]
I already changed the Level Names in Saturn so you didn't need to memorize what level was for what map.

**Comment by vanillaDSi** [comment]
> Did you mean to PR this on [GMM's custom maps fork](https://github.com/GlitchyMarioMario64/Saturn-Custom-Maps) and not the main Saturn repo?

Yes, I did. Sorry for the confusion!

**Comment by Llennpie** [comment]
All good.

**Pull request closed without merging**
